### ISSUE TITLE
Consider a release including a patch version

### ISSUE THREAD

**Issue by RoelofRuis** [sahmad98/go-ringbuffer#3]
Dear sahmad98,

Using go modules I seem unable to import your package directly, as the release tags are lacking a patch version.

As a workaround, for now I've forked this repository in order to create the an additional release including the patch version (`v1.1.0`).

You might want to add such a release to this repo as well, as it will make it easier for others to use the code. Also, I'd rather reference this repo, as future updates/fixes might be published here first.

If you don't feel like you want to add it, just close this issue :)

**Comment by sahmad98** [comment]
I have just added tag with patch version [here](https://github.com/sahmad98/go-ringbuffer/releases/tag/v1.1.0)

**Comment by RoelofRuis** [comment]
Perfect, thanks!
